version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: doctor-appointments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin